src/Entity/Formations.php
<?php

namespace App\Entity;

use App\Repository\FormationsRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=FormationsRepository::class)
 * @Vich\Uploadable
 */
class Formations
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $NomForm;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $refInterne;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @var string
     */
    private $image;

    /**
     * @Vich\UploadableField(mapping="featured_images", fileNameProperty="image")
     * @var File
     */
    protected $imageFile;

    /**
     * @ORM\ManyToOne(targetEntity=Domaines::class, inversedBy="formations")
     */
    private $domaines;

    /**
     * @ORM\ManyToOne(targetEntity=TypesFormation::class, inversedBy="formations")
     */
    private $TypesFormation;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dureeCentre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $dureeEntreprise;

    /**
     *@var \DateTime $createdAt;
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="date", nullable=true)
     */
    private $createdAt;

    /**
     * @var \DateTime $updateAt;
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="date", nullable=true)
     */
    private $updatedAt;

    /**
     * @ORM\OneToMany(targetEntity=Sessions::class, mappedBy="formation")
     */
    private $sessions;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="formation")
     */
    private $users;

    /**
     * @ORM\ManyToOne(targetEntity=NiveauxProfessionnels::class, inversedBy="formations")
     */
    private $niveauxProfessionnels;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $module;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $public;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $prerequis;

    /**
     * @ORM\Column(type="integer", length=255, nullable=true)
     */
    private $nbParticipants;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $orgPedag;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $methodePedag;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $moyenPedag;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $modSuivi;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $modEval;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $validation;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $profilIntervenants;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(max=255)
     */
    private $dateAcces;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $modAcces;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\Length(max=255)
     */
    private $lieu;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $tarif;

    


    public function __construct()
    {
        $this->sessions = new ArrayCollection();
        $this->users = new ArrayCollection();
    }
    public function __toString()
    {
        return $this->getNomForm();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomForm(): ?string
    {
        return $this->NomForm;
    }

    public function setNomForm(string $NomForm): self
    {
        $this->NomForm = $NomForm;

        return $this;
    }

    public function getRefInterne(): ?string
    {
        return $this->refInterne;
    }

    public function setRefInterne(?string $refInterne): self
    {
        $this->refInterne = $refInterne;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function setImageFile(?File $imageFile = null)
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function getDomaines(): ?Domaines
    {
        return $this->domaines;
    }

    public function setDomaines(?Domaines $domaines): self
    {
        $this->domaines = $domaines;

        return $this;
    }

    public function getTypesFormation(): ?TypesFormation
    {
        return $this->TypesFormation;
    }

    public function setTypesFormation(?TypesFormation $TypesFormation): self
    {
        $this->TypesFormation = $TypesFormation;

        return $this;
    }

    public function getDureeCentre(): ?int
    {
        return $this->dureeCentre;
    }

    public function setDureeCentre(?int $dureeCentre): self
    {
        $this->dureeCentre = $dureeCentre;

        return $this;
    }

    public function getDureeEntreprise(): ?int
    {
        return $this->dureeEntreprise;
    }

    public function setDureeEntreprise(?int $dureeEntreprise): self
    {
        $this->dureeEntreprise = $dureeEntreprise;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * @return Collection|Sessions[]
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Sessions $session): self
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions[] = $session;
            $session->setFormation($this);
        }

        return $this;
    }

    public function removeSession(Sessions $session): self
    {
        if ($this->sessions->removeElement($session)) {
            // set the owning side to null (unless already changed)
            if ($session->getFormation() === $this) {
                $session->setFormation(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users[] = $user;
            $user->addFormation($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeFormation($this);
        }

        return $this;
    }

    public function getNiveauxProfessionnels(): ?NiveauxProfessionnels
    {
        return $this->niveauxProfessionnels;
    }

    public function setNiveauxProfessionnels(?NiveauxProfessionnels $niveauxProfessionnels): self
    {
        $this->niveauxProfessionnels = $niveauxProfessionnels;

        return $this;
    }

    public function getModule(): ?string
    {
        return $this->module;
    }

    public function setModule(?string $module): self
    {
        $this->module = $module;

        return $this;
    }

    public function getPublic(): ?string
    {
        return $this->public;
    }

    public function setPublic(?string $public): self
    {
        $this->public = $public;

        return $this;
    }

    public function getPrerequis(): ?string
    {
        return $this->prerequis;
    }

    public function setPrerequis(?string $prerequis): self
    {
        $this->prerequis = $prerequis;

        return $this;
    }

    public function getNbParticipants(): ?string
    {
        return $this->nbParticipants;
    }

    public function setNbParticipants(?string $nbParticipants): self
    {
        $this->nbParticipants = $nbParticipants;

        return $this;
    }

    public function getOrgPedag(): ?string
    {
        return $this->orgPedag;
    }

    public function setOrgPedag(?string $orgPedag): self
    {
        $this->orgPedag = $orgPedag;

        return $this;
    }

    public function getMethodePedag(): ?string
    {
        return $this->methodePedag;
    }

    public function setMethodePedag(?string $methodePedag): self
    {

src/Form/FormationsType.php
<?php

namespace App\Form;

use App\Entity\Formations;
use Vich\UploaderBundle\Form\Type\VichImageType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;

class FormationsType extends AbstractType

/**
     * {@inheritdoc}
     */
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('NomForm', TextType::class, ['attr' => [
                'placeholder' => "ex: Gestionnaire de paye",
            ], 'label' => "NomForm *"])

            ->add('module')
            ->add('refInterne')
            ->add('description')
            ->add('imageFile', VichImageType::class, [
            'required' => false,
            'allow_delete' => true,
            'delete_label' => 'Supprimer',
            'download_label' => 'Télécharger',
            'download_uri' => true,
            'image_uri' => true,
            'asset_helper' => true,
        ])
            ->add('dureeCentre')
            ->add('dureeEntreprise')
            ->add('domaines')
            ->add('TypesFormation')
            ->add('niveauxProfessionnels')
            ->add('public', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('prerequis',TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('nbParticipants', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('orgPedag', TextareaType::class, ['attr' => ['maxlength'=> 255]])
            ->add('methodePedag', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('moyenPedag', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('modSuivi', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('modEval', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('validation', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('profilIntervenants', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('dateAcces', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('modAcces', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('lieu', TextareaType::class, ['attr' => ['maxlength' => 255]])
            ->add('tarif', TextareaType::class, ['attr' => ['maxlength' => 255]])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formations::class,
        ]);
    }
    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'appbundle_user';
    }
}

src/Controller/FormationsController.php
<?php

namespace App\Controller;

use App\Entity\Formations;
use App\Form\FormationsType;
use App\Repository\FormationsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("module/admin/formations")
 */
class FormationsController extends AbstractController
{
    /**
     * @Route("/", name="formations_index", methods={"GET"})
     */
    public function index(FormationsRepository $formationsRepository): Response
    {
        return $this->render('formations/index.html.twig', [
            'formations' => $formationsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formations_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formation = new Formations();
        $form = $this->createForm(FormationsType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formations_index');
        }

        return $this->render('formations/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formations_show", methods={"GET"})
     */
    public function show(Formations $formation): Response
    {
        return $this->render('formations/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formations_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formations $formation): Response
    {
        $form = $this->createForm(FormationsType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formations_index');
        }

        return $this->render('formations/edit.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formations_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formations $formation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formations_index');
    }
}

templates/formations/_delete_form.html.twig
<form method="post" action="{{ path('formations_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn btn3 btn-warning btn-block my-4">Supprimer</button>
</form>

templates/formations/_form.html.twig
{% block body %}

	<div class="bgimg-5" id="#">
		<div class="caption align-middle">
		 	<div class="row">
				<p class="admin offset-3 col-md-6 aos-init" data-aos="zoom-in" data-aos-offset="10" data-aos-duration="2000">"ADMINISTRATION GRETA COMPIEGNE".</p>
            </div>
			</div>
	</div>
	<div class="pres row">
		<div class="container c">
			<h1 class="text-center compte">Formation</h1>

            {{ form_start(form) }}
                
                <div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Nom de Formation *</label>
						{{form_widget(form.NomForm)}}
					</div>
					<div class="form-group col-md-6">
					<label class="">Ref Intern *</label>
                    {{ form_widget(form.refInterne)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Type Formation *</label>
                    {{ form_widget(form.TypesFormation)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Domaine *</label>
                    {{form_widget(form.domaines)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Niveau Professionnel *</label>
                    {{ form_widget(form.niveauxProfessionnels)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Module </label>
						{{form_widget(form.module)}}
					</div>
				</div>

                <div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Durée Centre </label>
                    {{ form_widget(form.dureeCentre)}}
					</div>
					<div class="form-group col-md-6">
					<label class="">Durée Entreprise </label>
                    {{form_widget(form.dureeEntreprise)}}
					</div>
				</div>

                <div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Image </label>
                    {{ form_widget(form.imageFile)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Description</label>
                    {{form_widget(form.description)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Public </label>
                    {{ form_widget(form.public)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Prérequis</label>
                    {{form_widget(form.prerequis)}}
					</div>
				</div>
				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Nombre de participants </label>
                    {{ form_widget(form.nbParticipants)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Organisation pédagogique</label>
                    {{form_widget(form.orgPedag)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Méthodes pédagogiques </label>
                    {{ form_widget(form.methodePedag)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Moyens pédagogiques</label>
                    {{form_widget(form.moyenPedag)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Modalités de suivi</label>
                    {{ form_widget(form.modSuivi)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Modalités d'évaluation</label>
                    {{form_widget(form.modEval)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Validation</label>
                    {{ form_widget(form.validation)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Profil des intervenants</label>
                    {{form_widget(form.profilIntervenants)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Dates ou delai d'accès</label>
                    {{ form_widget(form.dateAcces)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Modalités d'accès</label>
                    {{form_widget(form.modAcces)}}
					</div>
				</div>

				<div class="form-row">
					<div class="form-group col-md-6">
						<label class="">Lieu</label>
                    {{ form_widget(form.lieu)}}
					</div>
					<div class="form-group col-md-6">
						<label class="">Tarif</label>
                    {{form_widget(form.tarif)}}
					</div>
				</div>







                <div class="form-row">
                    <div class="form-group col-md-6">
                        <button class="btn btn1 btn-secondary btn-block my-4">Confirmer</button>
                    </div>
                    <div class="form-group col-md-6">
                        <a class="btn btn2 btn-primary btn-block my-4" type="submit" href="{{ path('formations_index')}}">Annuler</a>
                    </div>
                </div> 
            {{ form_end(form) }}
		</div>
	</div>

{% endblock body %}
           

templates/formations/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formations{% endblock %}

{% block body %}
    <h1>Edit Formations</h1>

    {{ include('formations/_form.html.twig', {'button_label': 'Update'}) }}

  
{% endblock %}

templates/formations/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations index{% endblock %}

{% block body %}
  <div class="bgimg-5" id="#">
    <div class="caption align-middle">
    <div class="row">
            <p class="admin offset-3 col-md-6 aos-init" data-aos="zoom-in" data-aos-offset="10" data-aos-duration="2000">"ADMINISTRATION GRETA COMPIEGNE".</p>
        </div>
    </div>
    </div>
    <div class="pres row">
        <div class="col-md-10 colonne-centree">
            <h2 class="text-center c stitle">Liste des Formations</h2>
                <table class="table col-auto table-condensed table-striped  gtitle mydatatable">
                    <thead>
                        <tr class="tr">
                            <th>NomForm</th>
                            <th>Type Formation</th>
                            <th>Domaine</th>
                            <th>Actions</th>
                            
                        </tr>
                    </thead>
                    <tbody>
                    {% for formation in formations %}
                        <tr>
                            <td data-label="{{ formation.NomForm }}" class="left">{{ formation.NomForm }}</td>
                            <td data-label="{{ formation.typesFormation }}" class="left">{{ formation.typesFormation }}</td>
                            <td data-label="{{ formation.domaines }}" class="left">{{ formation.domaines }}</td>
                            <td data-label="Action" class="left">
                                <a class="btn btn1 btn-secondary" href="{{ path('formations_show', {'id': formation.id}) }}">Afficher</a>
                                <a class="btn btn2 btn-primary" href="{{ path('formations_edit', {'id': formation.id}) }}">Modifier</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="10">Aucun enregistrement trouvé</td>
                         </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-10 colonne-centree">
            <a class="btn btn1 btn-secondary btn-block my-4" href="{{ path('formations_new') }}">Créer une Formation</a>
        </div>
    </div>
</div>

{% endblock %}

templates/formations/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formations{% endblock %}

{% block body %}
    <h1>Create new Formations</h1>

    {{ include('formations/_form.html.twig') }}

   <script>
    $(document).ready(function() {
        // you may need to change this code if you are not using Bootstrap Datepicker
        $('.js-datepicker').datepicker({
            format: 'yyyy-mm-dd'
        });
    });
</script>

{% endblock %}

templates/formations/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formations{% endblock %}

{% block body %}
    <div class="bgimg-5" id="#">
    <div class="caption align-middle">
        <div class="row">
            <p class="admin offset-3 col-md-6 aos-init" data-aos="zoom-in" data-aos-offset="10" data-aos-duration="2000">"ADMINISTRATION GRETA COMPIEGNE".</p>
        </div>
    </div>
    </div>
        <div class="pres row">
            <div class="col-md-10 colonne-centree">
                <h1 class="text-center compte">Formation</h1>
                <table class="table">
                <thead>
                <tr class="tr">
                    <th>NomForm</th>
                    <th>RefInterne</th>
                    <th>Image</th>
                    <th>Domaine</th>
                    <th>Niveau</th>
                    <th>DureeCentre</th>
                    <th>DureeEntreprise</th>
                    <th>UpdatedAt</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td data-label="{{ formation.NomForm }}" class="left">{{ formation.NomForm }}</td>
                    <td data-label="{{ formation.refInterne }}" class="left">{{ formation.refInterne }}</td>
                    <td data-label="{{ formation.image }}" class="d-none d-md-block left"><img class="img-thumbnail" src="{{ asset(vich_uploader_asset(formation, 'imageFile')) }}" alt="{{ formation.image }}"></td>
                    <td data-label="{{ formation.domaines }}" class="left">{{ formation.domaines }}</td>
                    <td data-label="{{ formation.niveauxProfessionnels }}" class="left">{{ formation.niveauxProfessionnels }}</td>
                    <td data-label="{{ formation.dureeCentre }}" class="left">{{ formation.dureeCentre }}</td>
                    <td data-label="{{ formation.dureeEntreprise }}" class="left">{{ formation.dureeEntreprise }}</td>
                    <td data-label="{{ formation.updatedAt|date }}" class="left">{{ formation.updatedAt|date }}</td>
                </tr>
        </tbody>
    </table>
     <div class="form-row">
                    <div class="form-group col-md-3">
                        <a class="btn btn1 btn-secondary btn-block my-4" href="{{ path('formations_edit', {'id': formation.id}) }}">Modifier</a>
                    </div>
                    <div class="form-group col-md-3">
                        <a class="btn btn2 btn-primary btn-block my-4" href="{{ path('formations_index', {'id': formation.id}) }}">Annuler</a>
                    </div>
                    <div class="form-group col-md-3">
                        <a class="btn btn4 btn-warning btn-block my-4" href="#">Désactiver</a>
                    </div>
                    <div class="form-group col-md-3">
                        {{ include('formations/_delete_form.html.twig') }}
                        
                </div>
            </div>  
        </div>
    </div>

{% endblock %}